name: flutter_form_builder
description: Package to build Material Form with fields like TextField, DropDown, Switches etc. with ability to create custom FormFields and composability and reuse validation functions.
version: 3.9.0
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/flutter_form_builder
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: 3.1.3
  intl: ^0.16.1
  # flutter_chips_input: ^1.9.0
  datetime_picker_formfield: ^1.0.0
  flutter_colorpicker: ^0.3.4
  # signature: ^2.0.0 - Doesn't implement onChanged, submitted PR. Meanwhile using local clone with onChanged
  validators: 3.0.0
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker
  flutter_touch_spin: ^1.0.1
  # image_picker: ^0.6.5+3
  rating_bar: ^0.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3

flutter:
